apiVersion: nais.io/v1alpha1
kind: Application
metadata:
  labels:
    app: hm-oppgave-sink
    team: teamdigihot
  name: hm-oppgave-sink
  namespace: teamdigihot
spec:
  image: {{ image }}
  team: teamdigihot
  liveness:
    path: /isalive
  readiness:
    path: /isready
  port: 8080
  prometheus:
    enabled: true
    path: /metrics
  replicas:
    max: 2
    min: 2
  resources:
    limits:
      cpu: 500m
      memory: 1024Mi
    requests:
      cpu: 200m
      memory: 512Mi
  secureLogs:
    enabled: true
  kafka:
    pool: nav-prod
  azure:
    application:
      enabled: true
