apiVersion: nais.io/v1alpha1
kind: Application
metadata:
  labels:
    app: hm-oppgave-sink
    team: teamdigihot
  name: hm-oppgave-sink
  namespace: teamdigihot
spec:
  image: {{ image }}
  team: teamdigihot
  liveness:
    path: /isalive
  readiness:
    path: /isready
  port: 8080
  prometheus:
    enabled: true
    path: /metrics
  replicas:
    max: 1
    min: 1
  resources:
    limits:
      cpu: 500m
      memory: 1024Mi
    requests:
      cpu: 200m
      memory: 512Mi
  env:
    - name: OPPGAVE_BASEURL
      value: https://digihot-proxy.dev-fss-pub.nais.io/oppgave-aad
    - name: PROXY_SCOPE
      value: api://dev-fss.teamdigihot.digihot-proxy/.default
    - name: OPPGAVE_BASEURL_Q1
      value: https://digihot-proxy-q1.dev-fss-pub.nais.io/oppgave-aad
    - name: PROXY_SCOPE_Q1
      value: api://dev-fss.teamdigihot.digihot-proxy-q1/.default
  secureLogs:
    enabled: true
  kafka:
    pool: nav-dev
  azure:
    application:
      enabled: true
