apiVersion: nais.io/v1alpha1
kind: Application
metadata:
  name: hm-oppgave-sink
  namespace: teamdigihot
  labels:
    team: teamdigihot
spec:
  image: {{ image }}
  team: teamdigihot
  liveness:
    path: /isalive
  readiness:
    path: /isready
  port: 8080
  prometheus:
    enabled: true
    path: /metrics
  replicas:
    min: 1
    max: 1
  resources:
    limits:
      cpu: 500m
      memory: 1024Mi
    requests:
      cpu: 200m
      memory: 512Mi
  env:
    - name: APPNAVN
      value: "{{ APPNAVN }}"
    - name: KAFKA_CONSUMER_GROUP_ID
      value: "{{ KAFKA_CONSUMER_GROUP_ID }}"
    - name: OPPGAVE_BASEURL
      value: "{{ OPPGAVE_BASEURL }}"
    - name: PDL_BASEURL
      value: "{{ PDL_BASEURL }}"
    - name: PROXY_SCOPE
      value: "{{ PROXY_SCOPE }}"
    - name: CONSUMED_EVENT_NAME
      value: "{{ CONSUMED_EVENT_NAME }}"
    - name: PRODUCED_EVENT_NAME
      value: "{{ PRODUCED_EVENT_NAME }}"
  secureLogs:
    enabled: true
  kafka:
    pool: nav-dev
  azure:
    application:
      enabled: true
